import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Security guide sidebar.
 *
 * SCAFFOLD STAGE: each chapter is represented by its overview page as a
 * flat doc link, grouped by Part with comment dividers. As a chapter's
 * full page set is authored, convert its entry into a
 * `{type:'category', link:{type:'doc', id:'<chapter>/<overview>'},
 *   items:[{type:'autogenerated', dirName:'<NN-chapter>'}]}`
 * block (the pattern used by the AI/web-dev guides).
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',

    // Part A · Foundations
    {
      type: 'category',
      label: '1. Security Foundations',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'foundations/foundations-overview'},
      items: [
        'foundations/cia-triad',
        'foundations/threat-vuln-risk',
        'foundations/attacker-mindset',
        'foundations/trust-boundaries',
        'foundations/defense-in-depth',
        'foundations/foundations-checkpoint',
      ],
    },
    {
      type: 'category',
      label: '2. Cryptography',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'cryptography/cryptography-overview'},
      items: [
        'cryptography/symmetric-encryption',
        'cryptography/asymmetric-encryption',
        'cryptography/hashing-and-macs',
        'cryptography/tls',
        'cryptography/pki-certificates',
        'cryptography/key-management',
        'cryptography/post-quantum',
        'cryptography/cryptography-checkpoint',
      ],
    },

    // Part B · Building secure software (AppSec)
    {
      type: 'category',
      label: '3. Web & Application Security',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'appsec/appsec-overview'},
      items: [
        'appsec/owasp-top-10',
        'appsec/injection',
        'appsec/xss',
        'appsec/broken-authentication',
        'appsec/broken-access-control',
        'appsec/ssrf',
        'appsec/deserialization-xxe',
        'appsec/defensive-patterns',
        'appsec/appsec-checkpoint',
      ],
    },
    {
      type: 'category',
      label: '4. Secure SDLC & DevSecOps',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'secure-sdlc/secure-sdlc-overview'},
      items: [
        'secure-sdlc/shift-left',
        'secure-sdlc/threat-modeling',
        'secure-sdlc/secure-design-review',
        'secure-sdlc/sast-dast-sca',
        'secure-sdlc/secrets-iac-container-scanning',
        'secure-sdlc/supply-chain',
        'secure-sdlc/secure-sdlc-checkpoint',
      ],
    },

    // Part C · Offensive
    {
      type: 'category',
      label: '5. Penetration Testing & Red Teaming',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'offensive/offensive-overview'},
      items: [
        'offensive/methodology',
        'offensive/rules-of-engagement',
        'offensive/reconnaissance',
        'offensive/exploitation',
        'offensive/post-exploitation',
        'offensive/reporting',
        'offensive/offensive-checkpoint',
      ],
    },

    // Part D · Defensive
    {
      type: 'category',
      label: '6. Detection & Response',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'detection/detection-overview'},
      items: [
        'detection/logging-telemetry',
        'detection/siem',
        'detection/detection-engineering',
        'detection/alerting-and-soc',
        'detection/threat-intel-attack',
        'detection/detection-checkpoint',
      ],
    },
    {
      type: 'category',
      label: '7. Incident Response & Forensics',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'incident-forensics/incident-forensics-overview'},
      items: [
        'incident-forensics/ir-lifecycle',
        'incident-forensics/chain-of-custody',
        'incident-forensics/forensic-artifacts',
        'incident-forensics/timeline-reconstruction',
        'incident-forensics/breach-determination',
        'incident-forensics/incident-forensics-checkpoint',
      ],
    },

    // Part E · Infrastructure & cloud security
    {
      type: 'category',
      label: '8. Network Security',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'network-security/network-security-overview'},
      items: [
        'network-security/segmentation',
        'network-security/firewalls-and-wafs',
        'network-security/ddos-mitigation',
        'network-security/vpn-and-secure-access',
        'network-security/egress-filtering',
        'network-security/zero-trust',
        'network-security/network-security-checkpoint',
      ],
    },
    {
      type: 'category',
      label: '9. Cloud & Identity Security',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'cloud-identity/cloud-identity-overview'},
      items: [
        'cloud-identity/iam-hardening',
        'cloud-identity/nhi-workload-identity',
        'cloud-identity/cspm',
        'cloud-identity/cloud-runtime-security',
        'cloud-identity/kubernetes-security',
        'cloud-identity/zero-trust-architecture',
        'cloud-identity/sso-federation',
        'cloud-identity/kms-secrets-at-scale',
        'cloud-identity/cloud-identity-checkpoint',
      ],
    },

    // Part F · Governance
    {
      type: 'category',
      label: '10. Compliance & Risk',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'compliance/compliance-overview'},
      items: [
        'compliance/frameworks',
        'compliance/controls-mapping',
        'compliance/audit-preparation',
        'compliance/risk-register',
        'compliance/vendor-risk',
        'compliance/compliance-checkpoint',
      ],
    },
    {
      type: 'category',
      label: '11. Securing AI Systems',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'ai-security/ai-security-overview'},
      items: [
        'ai-security/prompt-injection',
        'ai-security/llm-top-10',
        'ai-security/excessive-agency',
        'ai-security/mcp-security',
        'ai-security/ai-red-teaming',
        'ai-security/cardinal-rule',
        'ai-security/ai-security-checkpoint',
      ],
    },

    // Part G · Career & reference
    {
      type: 'category',
      label: '12. Security Career',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'career/career-overview'},
      items: [
        'career/roles',
        'career/certifications',
        'career/portfolio',
        'career/career-path',
        'career/mock-interviews',
        'career/career-checkpoint',
      ],
    },
    {
      type: 'category',
      label: '13. Case Studies',
      collapsible: true,
      collapsed: true,
      link: {type: 'doc', id: 'case-studies/case-studies-overview'},
      items: [
        'case-studies/supply-chain-case',
        'case-studies/cloud-misconfig-case',
        'case-studies/ransomware-case',
        'case-studies/generalizable-lessons',
        'case-studies/case-studies-checkpoint',
      ],
    },
    'glossary',
  ],
};

export default sidebars;
